version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://69.164.247.208:8000/api/v1}
    container_name: aso_frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - aso-network

networks:
  aso-network:
    name: aso_internal_network
    external: true
